"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { ArrowRight, Leaf, LockKeyhole, ShieldCheck } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

const users = { gerente: { pass: "admin123", rol: "ADMIN", nombre: "Gerente" }, packing: { pass: "pack123", rol: "SUPERVISOR", nombre: "Jefe de Packing" }, agronomo: { pass: "agro123", rol: "OPERADOR", nombre: "Ingeniero Agrónomo" } } as const;

export default function LoginPage() {
  const [user, setUser] = useState("");
  const [pass, setPass] = useState("");
  const [toast, setToast] = useState("");
  const [loading, setLoading] = useState(false);
  function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); const found = users[user as keyof typeof users]; window.setTimeout(() => { if (!found || found.pass !== pass) { setToast("Usuario o contraseña incorrectos."); setLoading(false); return; } window.localStorage.setItem("nativa-auth", JSON.stringify({ usuario: user, nombre: found.nombre, rol: found.rol })); setToast(`Acceso concedido como ${found.nombre}.`); window.setTimeout(() => { window.location.href = "/dashboard"; }, 400); }, 350); }
  return <main className="grid min-h-screen bg-white lg:grid-cols-2"><section className="relative hidden min-h-[420px] overflow-hidden bg-forest lg:block"><div className="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=1800&q=85')] bg-cover bg-center opacity-80" /><div className="absolute inset-0 bg-forest/65" /><div className="relative flex h-full flex-col justify-between p-10 text-white xl:p-16"><div><p className="font-display text-3xl font-bold">don ricardo<span className="text-lime">.</span></p><p className="mt-2 text-[10px] font-bold uppercase tracking-[.25em] text-white/55">Agrícola Don Ricardo</p></div><div className="max-w-lg"><div className="mb-5 flex h-12 w-12 items-center justify-center bg-lime text-forest"><Leaf size={24} /></div><h1 className="font-display text-5xl font-bold leading-[1.05]">La cosecha que llega más lejos.</h1><p className="mt-5 max-w-md text-sm leading-6 text-white/65">Controla la trazabilidad, valida la calidad y coordina cada despacho con claridad.</p></div><div className="flex items-center gap-2 text-xs text-white/50"><ShieldCheck size={15} className="text-lime" /> Plataforma segura para operaciones agroexportadoras</div></div></section><section className="flex items-center justify-center px-5 py-10 sm:px-10"><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .45 }} className="w-full max-w-md"><div className="mb-8 lg:hidden"><p className="font-display text-3xl font-bold text-forest">don ricardo<span className="text-rust">.</span></p></div><Card className="border-ink/10 shadow-sm"><CardHeader><p className="text-[10px] font-bold uppercase tracking-[.2em] text-rust">Portal de operaciones</p><CardTitle className="mt-2 text-3xl">Bienvenido de vuelta</CardTitle><p className="mt-2 text-sm text-ink/50">Ingresa para continuar con tu operación.</p></CardHeader><CardContent><form onSubmit={submit} className="space-y-5"><label className="block text-xs font-bold">Usuario<Input value={user} onChange={(event) => setUser(event.target.value)} className="mt-2" placeholder="Ej. gerente" autoComplete="username" /></label><label className="block text-xs font-bold">Contraseña<div className="relative mt-2"><LockKeyhole size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-ink/35" /><Input value={pass} onChange={(event) => setPass(event.target.value)} className="pl-9" placeholder="••••••••" type="password" autoComplete="current-password" /></div></label>{toast && <p role="status" className={`text-xs font-semibold ${toast.startsWith("Acceso") ? "text-emerald-700" : "text-red-600"}`}>{toast}</p>}<Button type="submit" className="w-full" disabled={loading}>{loading ? "Validando..." : "Ingresar al panel"}<ArrowRight size={16} /></Button></form><p className="mt-6 text-center text-[11px] text-ink/40">Acceso temporal de demostración · usa gerente, packing o agronomo</p></CardContent></Card></motion.div></section></main>;
}
