"use client";

import { Suspense, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Check, FileSearch, Package, ShieldCheck, Users, X } from "lucide-react";
import { IAAuditorGerencia } from "@/components/ai/IA_AuditorGerencia";
import { GestorDocumental } from "@/components/documentos/GestorDocumental";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useTraceabilityStore } from "@/store/useTraceabilityStore";

type Dispatch = { id: string; lote: string; destino: string; cajas: number; veredicto: "Aprobado" | "Rechazado"; estado: "Pendiente de firma" | "Liberado para Puerto" };
const initialDispatches: Dispatch[] = [{ id: "DSP-6008", lote: "LOT-24091", destino: "USA", cajas: 420, veredicto: "Aprobado", estado: "Pendiente de firma" }, { id: "DSP-6005", lote: "LOT-24082", destino: "China", cajas: 280, veredicto: "Aprobado", estado: "Pendiente de firma" }, { id: "DSP-5998", lote: "LOT-24074", destino: "UE", cajas: 180, veredicto: "Rechazado", estado: "Pendiente de firma" }];

function GerenteWorkspace() {
  const tab = useSearchParams().get("tab") ?? "panel";
  const router = useRouter();
  const [dispatches, setDispatches] = useState(initialDispatches);
  const [selected, setSelected] = useState<Dispatch | null>(null);
  const documentos = useTraceabilityStore((state) => state.documentos);
  function approve() { if (!selected || selected.veredicto === "Rechazado") return; const approved = { ...selected, estado: "Liberado para Puerto" as const }; setDispatches((items) => items.map((item) => item.id === selected.id ? approved : item)); setSelected(approved); }
  const authorization = <Card><CardHeader><CardTitle>Despachos pendientes de firma</CardTitle></CardHeader><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b border-gray-100 text-[10px] uppercase tracking-wider text-gray-400"><tr><th className="px-5 py-3">Despacho</th><th className="px-3 py-3">Lote</th><th className="px-3 py-3">Destino</th><th className="px-3 py-3">Cajas</th><th className="px-3 py-3">IA</th><th className="px-5 py-3 text-right">Estado</th></tr></thead><tbody>{dispatches.map((item) => <tr key={item.id} onClick={() => setSelected(item)} className="cursor-pointer border-b border-gray-100 hover:bg-gray-50"><td className="px-5 py-4 font-bold text-[#1B4332]">{item.id}</td><td className="px-3 py-4 font-semibold">{item.lote}</td><td className="px-3 py-4">{item.destino}</td><td className="px-3 py-4">{item.cajas}</td><td className="px-3 py-4"><span className={`rounded-full px-2 py-1 text-xs font-medium ${item.veredicto === "Aprobado" ? "bg-green-100 text-green-800" : "bg-red-100 text-red-800"}`}>{item.veredicto}</span></td><td className="px-5 py-4 text-right text-xs text-gray-500">{item.estado}</td></tr>)}</tbody></table></CardContent></Card>;
  let content: React.ReactNode;
  switch (tab) { case "autorizacion": content = authorization; break; case "auditoria": content = <IAAuditorGerencia />; break; case "usuarios": content = <Card><CardContent className="flex min-h-64 flex-col items-center justify-center text-center"><Users className="text-[#1B4332]" size={34} /><h2 className="mt-4 text-lg font-bold">Gestión de Usuarios</h2><p className="mt-2 text-sm text-gray-500">Administración de roles y accesos corporativos.</p></CardContent></Card>; break; default: content = <><div className="grid gap-4 sm:grid-cols-3"><Kpi icon={Package} label="Lotes procesados hoy" value="48" /><Kpi icon={ShieldCheck} label="Contenedores listos" value="12" /><Kpi icon={FileSearch} label="Alertas críticas" value="03" /></div><Card><CardHeader><CardTitle>Resumen ejecutivo</CardTitle></CardHeader><CardContent className="flex items-center justify-between gap-4"><p className="text-sm text-gray-500">{dispatches.filter((item) => item.estado === "Pendiente de firma").length} despachos esperan firma.</p><Button onClick={() => router.push("/gerente?tab=autorizacion")}>Revisar autorizaciones</Button></CardContent></Card></>; }
  return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#C9603F]">Gerencia ejecutiva</p><h1 className="mt-2 text-3xl font-bold">Supervisión de operaciones</h1><p className="mt-2 text-sm text-gray-500">Vista activa: {tab} · navegación sin recarga.</p></div>{content}{selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-5"><Card className="max-h-[90vh] w-full max-w-xl overflow-y-auto"><CardHeader className="flex flex-row items-start justify-between border-b border-gray-100"><div><p className="text-[10px] font-bold uppercase tracking-wider text-[#C9603F]">Expediente Digital</p><CardTitle className="mt-2">{selected.id} · {selected.lote}</CardTitle></div><Button variant="ghost" className="h-9 min-h-9 px-2" onClick={() => setSelected(null)}><X size={17} /></Button></CardHeader><CardContent className="space-y-5 p-5"><div className="grid grid-cols-2 gap-4"><Info label="Destino" value={selected.destino} /><Info label="Cajas" value={`${selected.cajas}`} /><Info label="Veredicto IA" value={selected.veredicto} /></div><GestorDocumental readOnly documentos={documentos} /><Button className="w-full" disabled={selected.veredicto === "Rechazado" || selected.estado === "Liberado para Puerto"} onClick={approve}><Check size={16} /> {selected.estado === "Liberado para Puerto" ? "Liberado para Puerto" : "Autorizar Despacho"}</Button></CardContent></Card></div>}</div>;
}
function Kpi({ icon: Icon, label, value }: { icon: typeof Package; label: string; value: string }) { return <Card className="shadow-sm"><CardContent className="p-5"><Icon size={19} className="text-[#1B4332]" /><p className="mt-4 text-xs text-gray-500">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></CardContent></Card>; }
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] font-bold uppercase tracking-wide text-gray-400">{label}</p><p className="mt-1 text-sm font-semibold text-gray-800">{value}</p></div>; }
export default function GerentePage() { return <Suspense fallback={<div className="p-6 text-sm text-gray-500">Cargando gerencia...</div>}><GerenteWorkspace /></Suspense>; }
