"use client";

import { useState } from "react";
import { Bell, Bot, ChevronDown, CircleHelp, LayoutGrid, Leaf, MapPin, Menu, PackageCheck, Search, Settings, ShieldCheck, Truck, X } from "lucide-react";

const lots = [
  { id: "LOT-24091", product: "Arándano Biloxi", farm: "Valle Azul · Ica", status: "En tránsito", statusColor: "bg-lime", progress: 78, temp: "2.8°C", eta: "Hoy, 18:40" },
  { id: "LOT-24088", product: "Uva Red Globe", farm: "Santa Elena · Piura", status: "Listo para despacho", statusColor: "bg-sky-200", progress: 100, temp: "3.4°C", eta: "Mañana, 06:20" },
  { id: "LOT-24082", product: "Mango Kent", farm: "El Mirador · Ancash", status: "Revisión fitosanitaria", statusColor: "bg-amber-300", progress: 51, temp: "5.1°C", eta: "En espera" },
];

function NavItem({ icon: Icon, label, active = false }: { icon: typeof LayoutGrid; label: string; active?: boolean }) {
  return <button className={`flex w-full items-center gap-3 px-3 py-2.5 text-left text-sm transition ${active ? "bg-lime text-ink" : "text-white/65 hover:bg-white/10 hover:text-white"}`}><Icon size={17} strokeWidth={1.8} /><span>{label}</span>{active && <span className="ml-auto h-1.5 w-1.5 rounded-full bg-forest" />}</button>;
}

export function Dashboard() {
  const [mobileNav, setMobileNav] = useState(false);
  const [query, setQuery] = useState("");
  const visibleLots = lots.filter((lot) => `${lot.id} ${lot.product} ${lot.farm}`.toLowerCase().includes(query.toLowerCase()));

  return <main className="min-h-screen bg-cream">
    <aside className={`fixed inset-y-0 left-0 z-30 flex w-64 flex-col bg-forest transition-transform lg:translate-x-0 ${mobileNav ? "translate-x-0" : "-translate-x-full"}`}>
      <div className="flex h-20 items-center justify-between border-b border-white/10 px-6"><div><p className="font-display text-2xl font-bold tracking-tight text-white">nativa<span className="text-lime">.</span></p><p className="mt-0.5 text-[10px] uppercase tracking-[.22em] text-white/40">control inteligente</p></div><button onClick={() => setMobileNav(false)} className="text-white/60 lg:hidden"><X size={20} /></button></div>
      <div className="px-3 pt-8"><p className="px-3 pb-3 text-[10px] font-bold uppercase tracking-[.2em] text-white/35">Operaciones</p><nav className="space-y-1"><NavItem icon={LayoutGrid} label="Resumen" active /><NavItem icon={PackageCheck} label="Trazabilidad" /><NavItem icon={Truck} label="Despachos" /><NavItem icon={Leaf} label="Calidad agrícola" /></nav><p className="px-3 pb-3 pt-8 text-[10px] font-bold uppercase tracking-[.2em] text-white/35">Administración</p><nav className="space-y-1"><NavItem icon={ShieldCheck} label="Cumplimiento" /><NavItem icon={Settings} label="Configuración" /></nav></div>
      <div className="mt-auto border-t border-white/10 p-5"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-rust text-xs font-bold text-white">MR</div><div><p className="text-sm font-semibold text-white">María Rojas</p><p className="text-xs text-white/45">Operaciones</p></div><ChevronDown size={15} className="ml-auto text-white/40" /></div></div>
    </aside>
    {mobileNav && <button aria-label="Cerrar menú" onClick={() => setMobileNav(false)} className="fixed inset-0 z-20 bg-ink/40 lg:hidden" />}
    <section className="lg:pl-64"><header className="flex h-20 items-center justify-between border-b border-ink/10 bg-cream/90 px-5 backdrop-blur md:px-10"><button onClick={() => setMobileNav(true)} className="text-ink lg:hidden"><Menu size={22} /></button><div className="hidden items-center gap-2 text-xs text-ink/50 md:flex"><MapPin size={15} /> Operación Perú <ChevronDown size={14} /></div><div className="ml-auto flex items-center gap-4"><button className="relative text-ink/55"><Bell size={19} /><span className="absolute -right-0.5 -top-0.5 h-2 w-2 rounded-full bg-rust" /></button><div className="h-6 w-px bg-ink/10" /><button className="flex items-center gap-2 text-sm font-semibold"><span className="hidden md:inline">Temporada 2024–25</span><ChevronDown size={15} /></button></div></header>
      <div className="grid-paper min-h-[calc(100vh-5rem)] px-5 py-8 md:px-10 md:py-11"><div className="mx-auto max-w-7xl"><div className="fade-up flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.18em] text-rust">Miércoles · 16 de septiembre, 2026</p><h1 className="font-display text-4xl font-bold tracking-tight text-ink md:text-5xl">Buenos días, María<span className="text-rust">.</span></h1><p className="mt-3 max-w-lg text-sm leading-6 text-ink/55">Todo bajo control. Hay <strong className="text-ink">2 puntos de atención</strong> que requieren una revisión antes del próximo despacho.</p></div><button className="flex w-fit items-center gap-2 bg-forest px-4 py-3 text-sm font-bold text-white transition hover:bg-ink"><Bot size={17} /> Consultar asistente</button></div>
        <div className="mt-9 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Lotes activos" value="48" detail="+12% vs. temporada anterior" accent="lime" /><Stat label="En tránsito" value="12" detail="2 llegan hoy" accent="sky" /><Stat label="Cumplimiento documental" value="94.8%" detail="+2.4% este mes" accent="rust" /><Stat label="Alertas abiertas" value="02" detail="Requieren atención" accent="amber" /></div>
        <div className="mt-8 grid gap-6 xl:grid-cols-[1fr_330px]"><section className="fade-up delay-1 border border-ink/10 bg-white/60"><div className="flex flex-col gap-4 border-b border-ink/10 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-display text-xl font-bold">Seguimiento de lotes</h2><p className="mt-1 text-xs text-ink/50">Actividad en tiempo real de tu cadena de suministro</p></div><div className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-ink/40" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar lote o producto" className="w-full border border-ink/15 bg-cream/50 py-2 pl-9 pr-3 text-xs outline-none placeholder:text-ink/40 focus:border-forest sm:w-52" /></div></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left"><thead className="bg-ink/[.025] text-[10px] uppercase tracking-[.14em] text-ink/45"><tr><th className="px-5 py-3 font-bold">Lote</th><th className="px-4 py-3 font-bold">Estado</th><th className="px-4 py-3 font-bold">Progreso</th><th className="px-4 py-3 font-bold">Temperatura</th><th className="px-5 py-3 font-bold">Llegada estimada</th></tr></thead><tbody className="divide-y divide-ink/10">{visibleLots.map((lot) => <tr key={lot.id} className="text-sm hover:bg-lime/10"><td className="px-5 py-4"><p className="font-bold">{lot.id}</p><p className="mt-1 text-xs text-ink/50">{lot.product} · {lot.farm}</p></td><td className="px-4 py-4"><span className="inline-flex items-center gap-2 text-xs font-semibold"><i className={`h-2 w-2 rounded-full ${lot.statusColor}`} />{lot.status}</span></td><td className="px-4 py-4"><div className="flex items-center gap-2"><div className="h-1.5 w-20 bg-ink/10"><div className="h-full bg-forest" style={{ width: `${lot.progress}%` }} /></div><span className="text-xs text-ink/50">{lot.progress}%</span></div></td><td className="px-4 py-4 text-xs font-semibold">{lot.temp}</td><td className="px-5 py-4 text-xs text-ink/55">{lot.eta}</td></tr>)}</tbody></table></div><div className="border-t border-ink/10 px-5 py-3"><button className="text-xs font-bold text-forest hover:text-rust">Ver todos los lotes <span aria-hidden="true">→</span></button></div></section>
          <aside className="fade-up delay-2 border border-ink/10 bg-forest p-6 text-white"><div className="flex items-start justify-between"><div className="flex h-10 w-10 items-center justify-center bg-lime text-forest"><Bot size={20} /></div><span className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-[.15em] text-lime"><i className="h-1.5 w-1.5 rounded-full bg-lime" /> En línea</span></div><h2 className="mt-7 font-display text-2xl font-bold leading-tight">Asistente<br />de campo</h2><p className="mt-3 text-sm leading-6 text-white/60">Consulta estados, normativas o recibe una recomendación basada en tus lotes activos.</p><div className="mt-8 space-y-2"><button className="flex w-full items-center justify-between border border-white/15 px-3 py-3 text-left text-xs text-white/70 hover:border-lime hover:text-white">¿Qué lotes necesitan revisión? <span>↗</span></button><button className="flex w-full items-center justify-between border border-white/15 px-3 py-3 text-left text-xs text-white/70 hover:border-lime hover:text-white">Resumen del despacho de hoy <span>↗</span></button></div><button className="mt-6 flex items-center gap-2 text-xs font-bold text-lime">Abrir asistente <span>→</span></button></aside></div>
        <div className="fade-up delay-3 mt-8 flex flex-col justify-between gap-3 border-t border-ink/10 pt-5 text-xs text-ink/45 sm:flex-row"><span>Última sincronización: hace 2 minutos</span><span className="flex items-center gap-2"><CircleHelp size={14} /> Centro de ayuda</span></div></div></div></section>
  </main>;
}

function Stat({ label, value, detail, accent }: { label: string; value: string; detail: string; accent: "lime" | "sky" | "rust" | "amber" }) { const colors = { lime: "bg-lime", sky: "bg-sky-200", rust: "bg-rust", amber: "bg-amber-300" }; return <div className="border border-ink/10 bg-white/60 p-5"><div className={`mb-5 h-1 w-8 ${colors[accent]}`} /><p className="text-xs font-semibold text-ink/55">{label}</p><p className="mt-1 font-display text-3xl font-bold tracking-tight">{value}</p><p className="mt-2 text-[11px] text-ink/45">{detail}</p></div>; }
